# Linux evdev backend mapping — auto-generated by manual_map_evdev.py
# {逻辑名: (类型, 内核码)}  类型: 'btn'=EV_KEY, 'abs'=EV_ABS
EVDEV_BTN_MAP = {
    'B': ('btn', 304),  # BTN_A
    'A': ('btn', 305),  # BTN_B
    'X': ('btn', 307),  # BTN_NORTH
    'Y': ('btn', 308),  # BTN_WEST
    'CAPTURE': ('btn', 309),  # BTN_Z
    'LB': ('btn', 310),  # BTN_TL
    'RB': ('btn', 311),  # BTN_TR
    'LT': ('btn', 312),  # BTN_TL2
    'RT': ('btn', 313),  # BTN_TR2
    'BACK': ('btn', 314),  # BTN_SELECT
    'START': ('btn', 315),  # BTN_START
    'HOME': ('btn', 316),  # BTN_MODE
    'L3': ('btn', 317),  # BTN_THUMBL
    'R3': ('btn', 318),  # BTN_THUMBR
}
EVDEV_AXIS_MAP = {
    'LS_X': ('abs', 0),  # ABS_X
    'LS_Y': ('abs', 1),  # ABS_Y
    'RS_X': ('abs', 3),  # ABS_RX
    'RS_Y': ('abs', 4),  # ABS_RY
}
# 十字键以 HAT(ABS_HAT0X=16 / ABS_HAT0Y=17)离散值出现; Y 轴 -1=上/ +1=下(屏幕坐标), 按下判定用方向符号:
EVDEV_HAT_MAP = {'DP_UP': (17, -1), 'DP_DOWN': (17, 1), 'DP_LEFT': (16, -1), 'DP_RIGHT': (16, 1)}  # (axis_code, value)
