#!/usr/bin/env python3
"""
Mesh separation script for AiSprayer parallel gripper.
Splits app/urdf/meshes/dobot_gazebo_sim/my_tools_fingers.stl into:
  - my_tools_finger_left.stl  (Side A: Component 0 + 1, negative Y region)
  - my_tools_finger_right.stl (Side B: Component 2 + 3, positive Y region)
Preserves original coordinate origins (0, 0, 0).
"""

import os
import shutil
import struct
import numpy as np
from scipy.sparse import csgraph, csr_matrix

def split_gripper_stl():
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    src_stl = os.path.join(project_root, "app/urdf/meshes/dobot_gazebo_sim/my_tools_fingers.stl")
    out_dir = os.path.join(project_root, "app/urdf/meshes/dobot_gazebo_sim")
    install_out_dir = os.path.join(project_root, "install/app/urdf/meshes/dobot_gazebo_sim")

    print(f"Reading input STL: {src_stl}")
    with open(src_stl, "rb") as f:
        header = f.read(80)
        count = struct.unpack("<I", f.read(4))[0]
        dtype = np.dtype([
            ('normal', '<f4', (3,)),
            ('v1', '<f4', (3,)),
            ('v2', '<f4', (3,)),
            ('v3', '<f4', (3,)),
            ('attr', '<u2')
        ])
        data = np.frombuffer(f.read(count * 50), dtype=dtype)

    print(f"Total facets: {count}")
    triangles = np.stack([data['v1'], data['v2'], data['v3']], axis=1)

    # Topological connected components
    scale = 10000.0
    v_int = np.round(triangles.reshape(-1, 3) * scale).astype(np.int64)
    unique_v, inverse = np.unique(v_int, axis=0, return_inverse=True)
    tri_indices = inverse.reshape(-1, 3)

    row, col = [], []
    for t in tri_indices:
        row.extend([t[0], t[1], t[2], t[1], t[2], t[0]])
        col.extend([t[1], t[2], t[0], t[0], t[1], t[2]])
    adj = csr_matrix((np.ones(len(row)), (row, col)), shape=(len(unique_v), len(unique_v)))
    n_components, labels = csgraph.connected_components(adj, directed=False)
    tri_comp = labels[tri_indices[:, 0]]

    # Left: components with Y < 0 (Components 0 and 1)
    # Right: components with Y > 0 (Components 2 and 3)
    left_mask = np.isin(tri_comp, [0, 1])
    right_mask = np.isin(tri_comp, [2, 3])

    left_data = data[left_mask]
    right_data = data[right_mask]

    print(f"Left finger facets: {len(left_data)}, Right finger facets: {len(right_data)}")

    def write_binary_stl(filename, facets):
        with open(filename, "wb") as f:
            f.write(b"STL generated by AiSprayer gripper mesh splitter".ljust(80, b"\0"))
            f.write(struct.pack("<I", len(facets)))
            f.write(facets.tobytes())
        print(f"Wrote {len(facets)} facets to {filename}")

    left_stl = os.path.join(out_dir, "my_tools_finger_left.stl")
    right_stl = os.path.join(out_dir, "my_tools_finger_right.stl")

    write_binary_stl(left_stl, left_data)
    write_binary_stl(right_stl, right_data)

    if os.path.exists(install_out_dir):
        shutil.copy2(left_stl, os.path.join(install_out_dir, "my_tools_finger_left.stl"))
        shutil.copy2(right_stl, os.path.join(install_out_dir, "my_tools_finger_right.stl"))
        print(f"Synchronized output to install directory: {install_out_dir}")

    # Verify bounds
    for name, facets in [("Left Finger", left_data), ("Right Finger", right_data)]:
        v = np.concatenate([facets['v1'], facets['v2'], facets['v3']], axis=0)
        print(f"{name} bounds:")
        print(f"  X: [{v[:,0].min():.2f}, {v[:,0].max():.2f}]")
        print(f"  Y: [{v[:,1].min():.2f}, {v[:,1].max():.2f}]")
        print(f"  Z: [{v[:,2].min():.2f}, {v[:,2].max():.2f}]")

if __name__ == "__main__":
    split_gripper_stl()
